name: stories_editor
description: stories editor made with flutter
version: 0.1.0
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  photo_view: ^0.13.0
  image: ^3.1.0
  photo_manager: ^1.3.10
  giphy_picker:
    git:
      url: https://github.com/camilo1498/giphy_picker
  perfect_freehand: ^1.0.4
  align_positioned: ^3.0.0
  path_provider: ^2.0.8
  image_gallery_saver: ^1.7.1
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya-VariableFont_wght.ttf
    - family: B612
      fonts:
        - asset: assets/fonts/B612-Regular.ttf
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
    - family: Varela
      fonts:
        - asset: assets/fonts/Varela-Regular.ttf
    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn-Regular.ttf
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf
    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf
    - family: YatraOne
      fonts:
        - asset: assets/fonts/YatraOne-Regular.ttf
    - family: OldStandardTT
      fonts:
        - asset: assets/fonts/OldStandardTT-Italic.ttf
    - family: Neonderthaw
      fonts:
        - asset: assets/fonts/Neonderthaw-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
    - family: SedgwickAve
      fonts:
        - asset: assets/fonts/SedgwickAve-Regular.ttf
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
    - family: FrederickatheGreat
      fonts:
        - asset: assets/fonts/FrederickatheGreat-Regular.ttf
    - family: ReenieBeanie
      fonts:
        - asset: assets/fonts/ReenieBeanie-Regular.ttf
    - family: BungeeShade
      fonts:
        - asset: assets/fonts/BungeeShade-Regular.ttf
    - family: UnifrakturMaguntia
      fonts:
        - asset: assets/fonts/UnifrakturMaguntia-Regular.ttf
